### ISSUE TITLE
Selecting previous month from spinner crashing the app

### ISSUE THREAD

**Issue by saikrupacg** [shagiz/AlmostMaterialDatepicker#9]
Select the minimum day as something like 19-Feb-2019. In months drop down still January is showing for the year 2019, if i select January month app is getting crashed. Below is the error info.

` java.lang.IllegalArgumentException: Invalid target position
        at androidx.recyclerview.widget.RecyclerView$SmoothScroller.start(RecyclerView.java:11534)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.startSmoothScroll(RecyclerView.java:8204)
        at androidx.recyclerview.widget.LinearLayoutManager.smoothScrollToPosition(LinearLayoutManager.java:451)
        at androidx.recyclerview.widget.RecyclerView.smoothScrollToPosition(RecyclerView.java:1781)
        at com.shagi.materialdatepicker.date.DayPickerView.scrollToMonth(DayPickerView.java:230)
        at com.shagi.materialdatepicker.date.DatePickerFragmentDialog$3.onMenuItemClick(DatePickerFragmentDialog.java:912)
        at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:105)
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:776)
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:923)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:913)
        at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:4064)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3822)`

**Comment by imkhalid** [comment]
@saikrupacg there was an issue of navigative value in this lib, i have forked it and resolved the crash, you can use this lib instead if you want.
 implementation 'com.github.imkhalid:AlmostMaterialDatepicker:1.0.13'
